#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="bg=#93a1a1,bold,underline"
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# set this so zprezto theme won't display myname@machine
export DEFAULT_USER=`whoami`

# Path for npm
# PATH=$PATH:${ZDOTDIR:-$HOME}/.npm-packages/bin
# export PATH

source "${ZDOTDIR:-$HOME}/.zshrc.local"

alias vi="nvim"
alias spacemacs="/usr/local/Cellar/emacs-plus/26.2/bin/emacs"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
