#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# set this so zprezto theme won't display myname@machine
export DEFAULT_USER=`whoami`

# Path for npm
PATH=$PATH:${ZDOTDIR:-$HOME}/.npm-packages/bin
export PATH

# source "${ZDOTDIR:-$HOME}/.bashrc"

alias vi="vim"

