" from thoughtbot
let mapleader = " "

set backspace=2
set nobackup
set nowritebackup
set noswapfile 
set history=50
set ruler

set autowrite
set laststatus=2

set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" display whitespace

set list listchars=tab:»·,trail:·,nbsp:·

" one space after punctuation
set nojoinspaces

" vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'tpope/vim-fugitive'

call vundle#end()
filetype plugin indent on
" end vundle

if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag -Q -l --nocolor --hidden -g "" %s'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

set textwidth=80
set colorcolumn=+1

" numbers
set number
set numberwidth=5


